### ISSUE TITLE
sn.correlation.isFinished() never reports finished

### ISSUE THREAD

**Issue by JustinWoodring** [PicoQuant/snAPI#25]
**Describe the bug**
Calling sn.correlation.measure() which should finish after 1 second never
updates sn.correlation.isFinished() with a value other than False.

**To Reproduce**
Call sn.correlation.measure().
Then inside a while loop check sn.correlation.isFinished()

**Expected behavior**
sn.correlation.isFinished() should return True after approximately 1 second

**Logfile**
Add corresponding logfile from C:\data\PicoQuant\Logs .
[240613.log](https://github.com/user-attachments/files/15829382/240613.log)

**Screenshots**
![image](https://github.com/PicoQuant/snAPI/assets/41842051/7b0bc919-ee7f-4262-bfd6-0335620966a8)

**Additional context**
System was working as expected but for some reason now only reports False.
I've tried restarting the MultiHarp device and my own computer.

**Comment by tpoint75** [comment]
This seems to be because the FCS is a bit slow. I improved the routine. Look for the next release.
The log file says that the data passed all buffers. But the correlation class is not finished yet. There will be a measurement finished log entry if it's done.

**Comment by tpoint75** [comment]
Are you using g2 or FCS-correlation? If FCS, pleas try the new FFCS method and report if  its working!
Thx Torsten.

**Comment by JustinWoodring** [comment]
Upon further experimentation, the issue was due to the overall slow process of correlating g2 which explains my rather mixed results. I was using g2 correlation, and after reducing various factors such as input intensity and ratio of bin width to acquisition time helped to resolve the issue.

**Comment by tpoint75** [comment]
Ahh, ok, I understand and thank you for your LinkedIn post!
