### ISSUE TITLE
Error while loading config file

### ISSUE THREAD

**Issue by etsc-clark** [PicoQuant/snAPI#26]
[PH330 snAPI problems.docx](https://github.com/user-attachments/files/15864176/PH330.snAPI.problems.docx)

**Comment by snizzleorg** [comment]
1.	There was an error when run configure loading, but no error message can be found.
 
<img width="168" alt="image" src="https://github.com/PicoQuant/snAPI/assets/1573482/d69d1fe8-9fa4-4db2-9c3a-81729e42d9b1">
<img width="416" alt="image" src="https://github.com/PicoQuant/snAPI/assets/1573482/d06782da-5f21-4c5e-960c-96fe161c2adb">

 
2.	Here when we use histogram.measure function, it returns a value of -5852671, not “ture” or “False”. We use TTL to C1 and C2 for triggering start and stop measurement. We need to know whether the device was ready to start, or we will lose some data. So how will the functions tell us it is ready or not?
 
<img width="416" alt="image" src="https://github.com/PicoQuant/snAPI/assets/1573482/f07d2d3f-1e0b-4a67-a9f7-50c708642e3f">
<img width="384" alt="image" src="https://github.com/PicoQuant/snAPI/assets/1573482/289ed5d0-3e04-49a7-945d-6658603f1103">

 
3.	I need to do repeat histogram measurements, each histogram integration time will be 1ms, that is to say, the repeat histogram speed will be about 1kHistogram/s. However, the device will take about 0.5s to initialize. I tried to do initialization at the beginning and repeat getting histogram, but each getdata() will cost 0.1s, and the repeat will stop with some reason then jump out of the loop.
<img width="176" alt="image" src="https://github.com/PicoQuant/snAPI/assets/1573482/703c8281-0975-4135-9d69-6584fcfdbc5c">


5.	I want to know the state of my input signals, C1, C2 and markers to make sure the signals can be used to do some logical usage of my software. I can’t find the functions to get the state of them in snAPI.

PicoHarp330 SN：1050871

**Comment by snizzleorg** [comment]
Are those problems connected? If not it would be better to submit individual issues.
With regard to the config file. Please post the content. Also please do post your python code so we can reproduce the issue here.

**Comment by tpoint75** [comment]
1. I improved the error output for the next release. I hope it is readable then! What language is set for windows? But anyways Error: 3 means:
The system cannot find the path specified.
2. You are right. I fixed the return type for the next release. But I expect that is ok if any different than 0 should be returned there at the moment. So you can ignore the return value there.
3. I don't think that this repead speeds are possible at the moment. You can try to implement your own routine with the data you get from the unfold class, but i don't know if python is fast enough at this point. What count rates are you using?
4. C1 and C2 is for starting and stopping measurements. But also this will not allow you make kHz rate start-stop-measurements. You also can get the marker with the unfold class only atm.
https://picoquant.github.io/snAPI/snAPI.Main.html#snAPI_Main_Unfold_isMarker
and
https://picoquant.github.io/snAPI/snAPI.Main.html#snAPI_Main_Unfold_markers

It seems to me, that you want to make something like FLIM with snAPI, but this is not implemented. There also dont exist a measurement class the returns an array of histograms. 

Please describe what you want to do, that we can implement the right classes you need.
