### ISSUE TITLE
Documentation about correlation is misleading

### ISSUE THREAD

**Issue by snizzleorg** [PicoQuant/snAPI#4]
The figure in 
(https://picoquant.github.io/snAPI/snAPI.Main.html#snAPI_Main_Correlation)

from the figure it appears that snAPI does not calculate the time differences between all photons, but rather focuses solely on those occurring in channel 2 immediately following channel 1, similar to the representation shown in the upper plot.

However snAPI indeed does calculate the time differences between all photons.

**Comment by tpoint75** [comment]
will be fixed in snAPI v1.0.2
