### ISSUE TITLE
modification of sys.excepthook leads to hidden tracebacks in Pycharm

### ISSUE THREAD

**Issue by ChrisOKay** [PicoQuant/snAPI#5]
**Describe the bug**
When importing snAPI, detailed traceback information is not shown in Pycharm.

**To Reproduce**
1. import snAPI
2. raise any Exception, e.g. raise TypeError()
3. Pycharm only shows "Process finished with exit code 1", but does not show the full traceback

**Expected behavior**
Traceback should be shown.

The root cause of this behaviour seems to be the "system-wide" modification of [sys.excepthook in Main.py](https://github.com/PicoQuant/snAPI/blob/e9bcca641fbe53566cee23e49fad5700277e332b/snAPI/Main.py#L298C21-L298C21) (sys.excepthook = logException). Disabling this statement re-enables the tracebacks.

**Comment by tpoint75** [comment]
Yes, the exceptions are directeded together with the snAPI messages to the stdout. We need them in the logfile too.
Isn't there a console window in pycharm? I would also prefer to use sn.logprint instead of print in python to have all messages in the snAPI log!

**Comment by tpoint75** [comment]
Hello Chris,
thank you for "give the exception back". I will add this to the next release!

I tried PyCharm and I see the console output and the exception!


![PyCharm](https://github.com/PicoQuant/snAPI/assets/717502/da08a061-880e-43c2-891d-7f0d915bb7c9)

**Comment by tpoint75** [comment]
The problem with this hook is to get the exceptions from elsewhere, where I can't set a try/except manually and I need the exception in the log to give goo support. If you have an better solution, just tell me.

**Comment by ChrisOKay** [comment]
Thanks for your feedback.
Regarding the console output: Yes, once sn is running, one can see this output.
But in our usecase, we have a general "driver"-package were everything gets imported and only instantiated on demand. So any import side-effects such as hidden exceptions are not desired.

Regarding the exceptions:
A highly philosophical question. IMHO it is not the API's job to log exceptions from external code, but only log/handle "internal" errors (with try/catch -> log constructs in the respective methods). External errors should be raised normally and be handled by the person who wrote the code.
If logging is desired for this external code, the person will take care of this logging themselves.
