### ISSUE TITLE
Option to suppress snAPI64.dll/initAPI -> "loadSettingsIni: <path_to_ini>" console output

### ISSUE THREAD

**Issue by ChrisOKay** [PicoQuant/snAPI#8]
**Is your feature request related to a problem? Please describe.**
This request is not related to a problem.
We are trying to keep our console output as minimal as possible. However, during initialization of snAPI, the dll call of [snAPI64.dll => initAPI](https://github.com/PicoQuant/snAPI/blob/e9bcca641fbe53566cee23e49fad5700277e332b/snAPI/Main.py#L381) leads to a seemingly unpreventable output of the used path ("loadSettingsIni: <path_to_ini>")

**Describe the solution you'd like**
I would like to have an option to suppress this message during the initAPI call. Ideally, it should be "auto-prevented" when setting [LogLevel] => API = 0. (I acknowledge that this could lead to a chicken-and-egg problem)

**Describe alternatives you've considered**
All [Log] and [LogLevel] within the system.ini are already disabled, which does not prevent the "loadSettingsIni" output.
I have tried to [suppress this output](https://stackoverflow.com/questions/2125702/how-to-suppress-console-output-in-python) via
```
with contextlib.redirect_stdout(None):
    sn = snAPI(libType=LibType.MH)
```
but the output still appears in the console.

**Comment by tpoint75** [comment]
No problem, i moved that to the API log level. I found some more uncategorized log entries and fixed them.. Thank you for reporting!

**Comment by tpoint75** [comment]
I think will make an new release this week!
